### PR TITLE
DTFS2-4545 - disable fetchWorkflowTypeB in portal scheduler jobs

### PR DESCRIPTION
**Pull request by ttbarnes**

### CODE REVIEW

**Review by pricea1 — COMMENTED** [review]
As this is the only job in scheduler we can switch it off by setting the env var DTFS_PORTAL_SCHEDULER='false'

or we could remove the initScheduler() from createApp.js

**Review by davehlewis — APPROVED** [review]
LGTM

**Comment by ttbarnes** [comment]
@pricea1 i'll update the environment variable. I think it's good to keep the workflow schedular task commented out though, just incase it needs to be renabled.

**Comment by ttbarnes** [comment]
Environment variable that enables the schedular now has false flag, so this PR is no longer needed.

**Comment by pricea1** [comment]
Odd its missing. If it's missing then the scheduler doesn't run. It only runs if DTFS_PORTAL_SCHEDULER=true.
The Azure dev portal-api has it set to false

**Pull request closed without merging**
